### PR TITLE
Distribute workloads by config during execution

### LINKED ISSUE #70: Bug: --startWarehouseIndex, --endWarehouseIndex and --stride parameters are ignored during distributed benchmark execution
### Description

When running TPC-C benchmark with `--startWarehouseIndex` and `--stride` parameters, these values are ignored and hardcoded defaults are used instead. This prevents proper distributed benchmarking across multiple instances.

### Steps to Reproduce

1. Build the project:
```bash
./mvnw clean package -P auroradsql
cd target
tar xvzf benchbase-auroradsql.tgz
cd benchbase-auroradsql
```

2. Run benchmark with custom warehouse parameters:
```bash
java -jar benchbase.jar \
  -b tpcc \
  -c config/auroradsql/sample_tpcc_config.xml \
  --startWarehouseIndex 3 \
  --endWarehouseIndex 2000 \
  --stride 3 \
  --terminals 466 \
  --execute true
```

### Expected Behavior

Workers should be created for warehouses: **3, 6, 9, 12, 15, 18, 21, ..., 1998**

### Actual Behavior

Workers are created for warehouses with irregular pattern: **5, 9, 13, 18, 22, 26, 31, 35, 39, ...**

The pattern does not follow the expected stride=3 distribution starting from warehouse 3.

### Root Cause

In `TPCCBenchmark.java`, the `createTerminalsOldWay()` method hardcodes the warehouse parameters instead of reading them from `WorkloadConfiguration`:

**Current code** (lines ~96-98):
https://github.com/amazon-contributing/aurora-dsql-benchbase-benchmarking/blob/dsql/src/main/java/com/oltpbenchmark/benchmarks/tpcc/TPCCBenchmark.java#L96-L98
```java
// Default values used for warehouse indexes and stride
final int startWarehouseIndex = 1;
final int endWarehouseIndex = totalWarehouses;
final int stride = 1;
```

This ignores the command-line parameters `--startWarehouseIndex`, `--endWarehouseIndex`, and `--stride`.

### Proposed Fix

Replace the hardcoded values with values from `WorkloadConfiguration`, using defaults only when not specified:

```java
// Get values from WorkloadConfiguration, use defaults if not set
final int startWarehouseIndex = workConf.getStartWarehouseIndex() > 0
    ? workConf.getStartWarehouseIndex()
    : 1;
final int endWarehouseIndex = workConf.getEndWarehouseIndex() > 0
    ? workConf.getEndWarehouseIndex()
    : totalWarehouses;
final int stride = workConf.getStride() > 0
    ? workConf.getStride()
    : 1;
```

### Impact

This bug prevents users from:
- Running distributed benchmarks across multiple instances with proper warehouse partitioning
- Following the documented "Advanced: Multi-Instance Distributed Benchmarking across AZs" approach in the README
- Achieving optimal performance testing as described in the documentation (Benchmarks can be run even with this bug, but since the expected warehouse is not selected, there are many DSQL OCC conflicts.)

### Environment

- Repository: amazon-contributing/aurora-dsql-benchbase-benchmarking
- Branch: dsql
- File: `src/main/java/com/oltpbenchmark/benchmarks/tpcc/TPCCBenchmark.java`
- Method: `createTerminalsOldWay()`

### Additional Notes

The README documentation describes distributed benchmarking with stride-based warehouse distribution, but the implementation does not support this feature due to the hardcoded values.

### PR DESCRIPTION
**Pull request by HanzhouTang**
This PR fixes the workload distribution logic to respect configuration settings during execution. Also adds unit test.

Fixes https://github.com/amazon-contributing/aurora-dsql-benchbase-benchmarking/issues/70

*Issue #, if available:* #70

*Description of changes:*

Fix warehouse distribution to read `startWarehouseIndex`, `endWarehouseIndex`, and `stride` from config instead of using hardcoded values. This enables distributed benchmarking across multiple instances.

Also adds unit tests to verify stride-based distribution and prevent regression.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/main/java/com/oltpbenchmark/benchmarks/tpcc/TPCCBenchmark.java [hunk 1]
```diff
@@ -86,16 +86,10 @@ private List<TPCCWorker> createTerminalsOldWay() throws SQLException {
...
-    }
-
-    // Default values used for warehouse indexes and stride
-    final int startWarehouseIndex = 1;
-    final int endWarehouseIndex = totalWarehouses;
-    final int stride = 1;
+    // [startWarehouseIndex, endWarehouseIndex] are both included.
+    final int startWarehouseIndex = workConf.getStartWarehouseIndex();
+    final int endWarehouseIndex = workConf.getEndWarehouseIndex();
+    final int stride = workConf.getStride();
```
Comment (Alif-2001) [inline src/main/java/com/oltpbenchmark/benchmarks/tpcc/TPCCBenchmark.java]: Should we default to startWarehouseIndex = 1, endWarehouseIndex = totalWarehouses and stride = 1 if workConfig doesn't have the values set for those attributes?

Comment (HanzhouTang) [reply src/main/java/com/oltpbenchmark/benchmarks/tpcc/TPCCBenchmark.java]: Sure, thanks for the callout.

**Review by Alif-2001 — APPROVED** [review]
